# Generated by Django 3.0.7 on 2020-10-03 14:50

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended',
            name='url',
            field=models.CharField(default=1, max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_http]),
            preserve_default=False,
        ),
    ]
