# Generated by Django 3.0.7 on 2020-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_extended_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended',
            name='url',
            field=models.CharField(max_length=220),
        ),
    ]
