# Generated by Django 3.0.7 on 2020-10-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201003_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extended',
        ),
    ]
